#!/bin/bash
# ============================================================================================
# A-3 step 5c: repack with the annotation actually set.
#
# 🔴 WHY THERE IS A SECOND PACK. The first used ovftool's --annotation option. It did not
#    replace the annotation -- it ERASED it: the packed OVF came out with an AnnotationSection
#    containing no <Annotation> element at all, 0 characters, where the artefact it was built
#    from had a full one. Control C caught it. Had I checked "did ovftool exit 0" or "is there
#    an AnnotationSection", both would have said yes.
#
#    This is the H-26 annotation defect a second time, inverted. There the annotation survived
#    a repack unchanged and therefore described the wrong contents; here it did not survive at
#    all. Same underlying error in both: treating the annotation as something the packer will
#    look after, instead of reading back what the product declares.
#
# THE FIX stays inside the "do not hand-write the descriptor" rule. The .vmx is generated by
# ovftool from the current shipping .ova and already carries `annotation = "..."`. That is a
# plain key = value file, so the annotation is set THERE and ovftool still generates the OVF
# and the manifest itself. Nothing hand-writes an OVF or a SHA line.
#
# The flattened vmdk from the previous pack is reused unchanged -- it is the disk that was
# already produced from the powered-off guest, and re-converting it would only add risk.
#
# [Co-developed with claude code -- Adam]
# ============================================================================================
set -u
T=/home/nslab/ovftool-dist/ovftool/ovftool
W=/home/nslab/a3repack
SRC=/home/nslab/repack/out/NDTwin-P4-demo.ova
ANN=/home/nslab/annotation.txt
VMX="$W/NDTwin-P4-demo.vmx"

echo "=== $(date -Is) A-3 pack (2) ==="
[ -s "$VMX" ] || { echo "no vmx"; exit 1; }
[ -s "$W/NDTwin-P4-demo-disk1.vmdk" ] || { echo "no flattened disk"; exit 1; }

echo
echo "=== R1. set the annotation in the .vmx (key = value, not an OVF descriptor) ==="
python3 - "$VMX" "$ANN" <<'PY'
import sys,io
vmx,ann=sys.argv[1],sys.argv[2]
text=open(ann,encoding='utf-8').read().strip()
assert '"' not in text, "annotation contains a double quote; vmx would need escaping"
lines=open(vmx,encoding='utf-8',errors='replace').read().splitlines()
out=[];seen=False
for L in lines:
    if L.lower().startswith('annotation ='):
        out.append('annotation = "%s"'%text); seen=True
    else:
        out.append(L)
if not seen:
    out.append('annotation = "%s"'%text)
open(vmx,'w',encoding='utf-8').write("\n".join(out)+"\n")
print("  annotation set: %d chars, replaced=%s"%(len(text),seen))
PY
echo "  read back from the vmx (first 120 chars):"
grep -i '^annotation =' "$VMX" | cut -c1-120 | sed 's/^/    /'

echo
echo "=== R2. pack again: no --lax, hw version capped, NO --annotation option ==="
rm -f "$W/out/NDTwin-P4-demo.ova"
"$T" --maxVirtualHardwareVersion=14 "$VMX" "$W/out/NDTwin-P4-demo.ova" 2>&1 \
  | tr '\r' '\n' | grep -vE 'Disk progress|^$' | tail -4
[ -s "$W/out/NDTwin-P4-demo.ova" ] || { echo "🔴 no artefact -- STOP"; exit 1; }

echo
echo "=== R3. CONTROL A -- hardware identity, read back from the product ==="
rm -rf "$W/peek"; mkdir -p "$W/peek"; cd "$W/peek" || exit 1
tar -xf "$W/out/NDTwin-P4-demo.ova" --wildcards '*.ovf'
N=$(grep -oE '<Name>[^<]*' ./*.ovf | head -1 | sed 's/<Name>//')
V=$(grep -oE '<vssd:VirtualSystemType>[^<]*' ./*.ovf | head -1 | sed 's/.*>//')
[ "$N" = "NDTwin-P4-demo" ] && echo "  PASS: <Name> = $N" || echo "  🔴 FAIL: <Name> = '$N'"
[ "$V" = "vmx-14" ]         && echo "  PASS: VirtualSystemType = $V" || echo "  🔴 FAIL: VirtualSystemType = '$V'"
grep -oE 'vmware\.sata\.ahci|E1000|lsilogic' ./*.ovf | sort -u | sed 's/^/    declared: /'
grep -oE '<rasd:VirtualQuantity>[0-9]*' ./*.ovf | head -2 | sed 's/^/    /'

echo
echo "=== R4. CONTROL C -- does the declaration DESCRIBE the content? ==="
python3 - "$PWD" <<'PY'
import glob,sys,html,re
ovf=glob.glob(sys.argv[1]+'/*.ovf')[0]
t=open(ovf,encoding='utf-8',errors='replace').read()
m=re.search(r'<Annotation>(.*?)</Annotation>', t, re.S)
ann=html.unescape(m.group(1)) if m else ''
print(f"    annotation length in the OVF: {len(ann)} chars")
checks={
 'doc/ removal stated':'doc/',
 'NTV pinned commit b5e039c':'b5e039c',
 'the absent endpoint named':'disable_switch',
 'public snapshot named':'NDTwin-Kernel-P4-public',
 'Energy-Saving-App':'Energy-Saving-App',
 'Simulation-Platform-Manager':'Simulation-Platform-Manager',
 'Traffic-Engineering-App':'Traffic-Engineering-App',
 'Network-Traffic-Visualizer':'Network-Traffic-Visualizer',
 'the Main-Class jar warning':'Main-Class',
}
bad=0
for label,needle in checks.items():
    ok=needle in ann
    print(f"    [{'PASS' if ok else 'FAIL'}] {label}")
    if not ok: bad+=1
print("    ==> ✅ the annotation describes the new content" if bad==0
      else f"    ==> 🔴 {bad} thing(s) missing from the annotation")
PY

echo
echo "=== R5. CONTROL B -- import conversion, PAIRED, each arm in its own fresh empty dir ==="
rm -rf "$W/cb_pos" "$W/cb_neg"; mkdir -p "$W/cb_pos" "$W/cb_neg"
echo "  pos dir empty: $([ -z "$(ls -A "$W/cb_pos")" ] && echo yes || echo NO)"
echo "  neg dir empty: $([ -z "$(ls -A "$W/cb_neg")" ] && echo yes || echo NO)"
POUT=$("$T" "$W/out/NDTwin-P4-demo.ova" "$W/cb_pos/imp.vmx" 2>&1 | tr '\r' '\n' | grep -vE 'Disk progress|^$')
echo "  POSITIVE arm:"; echo "$POUT" | tail -3 | sed 's/^/    /'
PV=$(echo "$POUT" | grep -qE 'Completed successfully' && echo 0 || echo 1)
echo "    verdict: $PV  <-- must be 0"
cp "$W/out/NDTwin-P4-demo.ova" "$W/cb_neg/flip.ova"
SZ=$(stat -c%s "$W/cb_neg/flip.ova")
printf '\xff' | dd of="$W/cb_neg/flip.ova" bs=1 seek=$(( SZ / 2 )) count=1 conv=notrunc status=none
NOUT=$("$T" "$W/cb_neg/flip.ova" "$W/cb_neg/z.vmx" 2>&1 | tr '\r' '\n' | grep -vE 'Disk progress|^$')
echo "  NEGATIVE arm (byte flipped at $(( SZ / 2 )) of $SZ):"; echo "$NOUT" | tail -3 | sed 's/^/    /'
NV=$(echo "$NOUT" | grep -qE 'Completed successfully' && echo 0 || echo 1)
echo "    verdict: $NV  <-- must be 1"
if [ "$PV" = 0 ] && [ "$NV" = 1 ]; then
  echo "  ✅ PASS: arms DIFFER -- the check discriminates"
else
  echo "  🔴 FAIL: arms did not differ (pos=$PV neg=$NV)"
fi
rm -rf "$W/cb_pos" "$W/cb_neg"

echo
echo "=== R6. identity of the artefact that ships ==="
stat -c '  %n  %s bytes' "$W/out/NDTwin-P4-demo.ova"
sha256sum "$W/out/NDTwin-P4-demo.ova" | sed 's/^/  /'
OLD=$(stat -c%s "$SRC"); NEW=$(stat -c%s "$W/out/NDTwin-P4-demo.ova")
echo "  old (72fac128...): $OLD bytes"
echo "  new:               $NEW bytes"
echo "  smaller by:        $(( OLD - NEW )) bytes = $(( (OLD-NEW)/1048576 )) MiB"
echo "PACK2_DONE"
