#!/bin/bash
printf "%s %s %s %s\n" "${NOLAB_SUITE:--}" "${NOLAB_PASS:--}" "$(basename "$0")" "$*" >> "${NOLAB_LOG:-/dev/null}"
case " $* " in
    *" show "*|*" list "*|*" -o link"*|*" link show"*|*" addr show"*|*" -V "*|*" --version "*|*" get "*|*" find "*|*" dump-flows "*|*" dump-ports "*)
        case " $* " in *" netns "*|*" exec "*) ;; *) exec "/usr/sbin/tc" "$@" ;; esac ;;
esac
echo "tc: refused by the nolab shim (a changing or namespace form)" >&2
exit 1
