#!/usr/bin/env python3
"""Regenerate p4runtime's generated modules for the protobuf runtime of THIS interpreter.

Run it once, with the venv's own interpreter, right after installing the requirements:

    python3 -m venv p4_proxy/venv
    p4_proxy/venv/bin/pip install -r p4_proxy/requirements.txt
    p4_proxy/venv/bin/python p4_proxy/regen_p4runtime_pb2.py

WHY. p4runtime 1.5.0 -- the newest release on PyPI -- ships p4/v1/*_pb2.py and
p4/config/v1/*_pb2.py generated by a pre-3.19 protoc: they build descriptors directly
(`create_key=_descriptor._internal_create_key`), and every protobuf since 4.21 refuses that on its
default backend ("Descriptors cannot be created directly"). The proxy then cannot even import
p4_client. protobuf 3.20.3, the last release that accepted them, carries CVE-2025-4565 and
CVE-2026-0994, so requirements.txt moves protobuf forward and this script moves the generated code
with it.

HOW, with nothing downloaded. The wheel carries no .proto files, but every old module embeds its
complete FileDescriptorProto (`DESCRIPTOR.serialized_pb`). This script imports the old modules on
the pure-Python backend (the one backend that still accepts them), writes those descriptors as a
FileDescriptorSet, and runs the protoc bundled in grpcio-tools over it (`--descriptor_set_in`).

WHAT IT CHECKS BEFORE IT REPLACES ANYTHING. The new modules are imported in a separate interpreter
on the DEFAULT backend, from a scratch directory, and each one's FileDescriptorProto must be
byte-for-byte the one the old module embedded -- the schema cannot change, only the code shape.
Any difference and nothing is written. Afterwards the installed package is imported once more,
again on the default backend. Exit 0 only when that works.

Idempotent: on a venv it has already regenerated it finds nothing to replace and says so. A
`pip install --force-reinstall p4runtime` puts the old modules back; run it again after one.
On protobuf 3.x it does nothing (the shipped modules import there).

[Co-developed with claude code -- Adam]
"""
import os

# Before ANY google.protobuf import: the old modules import only on the pure-Python backend.
# The checks below run in child interpreters with this variable removed, i.e. on the default.
_CALLER_IMPL = os.environ.get("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION")
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

import hashlib  # noqa: E402
import importlib  # noqa: E402
import shutil  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402
import tempfile  # noqa: E402

P4_PROTOS = ["p4/config/v1/p4types.proto", "p4/config/v1/p4info.proto",
             "p4/v1/p4data.proto", "p4/v1/p4runtime.proto"]
# Resolved by protoc but NOT regenerated: they belong to protobuf and googleapis-common-protos,
# whose own modules are current. Listed in dependency order, ahead of the p4 files.
DEPENDENCY_MODULES = ["google.protobuf.any_pb2", "google.rpc.status_pb2"]
PACKAGE_INITS = ["__init__.py", "config/__init__.py", "config/v1/__init__.py", "v1/__init__.py"]

_VERIFY = r"""
import importlib, os, sys
old = {}
for line in open(sys.argv[1], "rb"):
    name, hx = line.rstrip(b"\n").split(b"\0")
    old[name.decode()] = bytes.fromhex(hx.decode())
want_root = sys.argv[2]
from google.protobuf.internal import api_implementation
bad = 0
for name, blob in old.items():
    mod = importlib.import_module(name[:-len(".proto")].replace("/", ".") + "_pb2")
    if want_root and not os.path.realpath(mod.__file__).startswith(os.path.realpath(want_root)):
        print(f"  {name}: imported from {mod.__file__}, not from {want_root}"); bad += 1; continue
    same = mod.DESCRIPTOR.serialized_pb == blob[:-1]  # MUTANT
    print(f"  {name:30s} descriptor {'identical' if same else 'DIFFERS'} ({len(blob)} bytes)")
    bad += not same
importlib.import_module("p4.v1.p4runtime_pb2_grpc")
print(f"  backend {api_implementation.Type()}, p4runtime_pb2_grpc imports")
sys.exit(1 if bad else 0)
"""


def sha(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def default_backend_env(extra_path=None):
    env = {k: v for k, v in os.environ.items() if k != "PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"}
    if extra_path:
        env["PYTHONPATH"] = extra_path
    else:
        env.pop("PYTHONPATH", None)
    return env


def main():
    if _CALLER_IMPL is not None:
        print(f"note: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION={_CALLER_IMPL} in the caller's "
              "environment is ignored for the checks -- they run on the default backend")
    import google.protobuf
    major = int(google.protobuf.__version__.split(".")[0])
    if major < 4:
        print(f"protobuf {google.protobuf.__version__}: p4runtime's shipped modules import as they "
              "are; nothing to regenerate.")
        return 0
    try:
        import grpc_tools  # noqa: F401
    except ImportError:
        print("grpcio-tools is not installed in this interpreter; it is in "
              "p4_proxy/requirements.txt -- install that file first.", file=sys.stderr)
        return 2

    from google.protobuf import descriptor_pb2
    import p4
    site_p4 = os.path.dirname(os.path.realpath(p4.__file__))
    if not site_p4.startswith(os.path.realpath(sys.prefix) + os.sep):
        print(f"refusing: the p4 package at {site_p4} is not inside this interpreter's prefix "
              f"({sys.prefix}). Run this with the venv's own python.", file=sys.stderr)
        return 2

    work = tempfile.mkdtemp(prefix="regen_p4runtime_")
    try:
        fds = descriptor_pb2.FileDescriptorSet()
        old = {}
        for mod_name in DEPENDENCY_MODULES + [p[:-6].replace("/", ".") + "_pb2" for p in P4_PROTOS]:
            mod = importlib.import_module(mod_name)
            fdp = descriptor_pb2.FileDescriptorProto.FromString(mod.DESCRIPTOR.serialized_pb)
            fds.file.append(fdp)
            old[fdp.name] = mod.DESCRIPTOR.serialized_pb
        set_path = os.path.join(work, "p4runtime.fds")
        with open(set_path, "wb") as f:
            f.write(fds.SerializeToString())
        old_path = os.path.join(work, "old_descriptors.txt")
        with open(old_path, "wb") as f:
            for name in P4_PROTOS:
                f.write(name.encode() + b"\0" + old[name].hex().encode() + b"\n")

        gen = os.path.join(work, "gen")
        os.makedirs(gen)
        cmd = [sys.executable, "-m", "grpc_tools.protoc", f"--descriptor_set_in={set_path}",
               f"--python_out={gen}", f"--grpc_python_out={gen}"] + P4_PROTOS
        subprocess.run(cmd, check=True)
        for init in PACKAGE_INITS:   # make the scratch copy a regular package, like the installed one
            src = os.path.join(site_p4, init)
            if os.path.exists(src):
                os.makedirs(os.path.dirname(os.path.join(gen, "p4", init)), exist_ok=True)
                shutil.copyfile(src, os.path.join(gen, "p4", init))

        print("checking the generated modules (default backend, scratch copy):")
        rc = subprocess.run([sys.executable, "-c", _VERIFY, old_path, os.path.join(gen, "p4")],
                            env=default_backend_env(gen), cwd=work).returncode
        if rc != 0:
            print("refusing: the generated modules do not reproduce the shipped schema; nothing "
                  "was replaced.", file=sys.stderr)
            return 1

        replaced = 0
        for proto in P4_PROTOS:
            for suffix in ("_pb2.py", "_pb2_grpc.py"):
                rel = proto[len("p4/"):-len(".proto")] + suffix
                src, dst = os.path.join(gen, "p4", rel), os.path.join(site_p4, rel)
                if not os.path.exists(src):
                    continue
                before = sha(dst) if os.path.exists(dst) else "<absent>"
                if before == sha(src):
                    continue
                shutil.copyfile(src, dst)
                print(f"replaced {os.path.join('p4', rel):34s} {before} -> {sha(dst)}")
                replaced += 1
        for root, dirs, _ in os.walk(site_p4):
            if "__pycache__" in dirs:
                shutil.rmtree(os.path.join(root, "__pycache__"))
        if not replaced:
            print("already current: every generated module matches what is installed.")

        print("checking the installed package (default backend):")
        rc = subprocess.run([sys.executable, "-c", _VERIFY, old_path, site_p4],
                            env=default_backend_env(), cwd=work).returncode
        if rc != 0:
            print("the installed package does not import on the default backend.", file=sys.stderr)
            return 1
        print(f"ok: {site_p4} imports on the default backend with the shipped schema.")
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
