#!/usr/bin/env bash
printf '%s ALLOWED-LAUNCH simple_switch pid=%s argv0=%s args=%s\n' "$(date +%s.%N)" "$$" "${NDT_HB_CHECK_ARGV0:-?}" "$*" >> "$NOLAB_LOG"
exec -a "${NDT_HB_CHECK_ARGV0:-ndt-hbdrop-bmv2}" /usr/local/bin/simple_switch "$@"
